name: release

on:
  push:
    tags:
      - "*"

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: build
        run: |
          sudo apt-get install -y libxi-dev
          go get -t ./...
          go build -o autorotate
          zip -r "autorotate-$GITHUB_REF_NAME.zip" autorotate
      # - name: version
      #   run: echo "{version}::{$(./bin/autorotate version --short)}"
      #   id: version

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./autorotate-${{ github.ref_name }}.zip
            ./autorotate
