name: Publish GitHub Actions with Artifacts

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9].*"

jobs:
       
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:

      - name: Step 1 - get repo
        run: git clone 'https://github.com/undg/autorotate'
        
      - name: Step 2 - build binary and add to artifacts
        run: |
          mkdir build
          cd autorotate
          go build -o ../build
          cd ..
    
      - name: Step 3 - Use the Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: build
